language: java

before_install:
    - git clone https://github.com/hy-ohtu/PaivanUutiset.git
    - mvn clean install -f PaivanUutiset/pom.xml
    - git clone https://github.com/hy-ohtu/HackerNewsUutiset.git
    - mvn clean install -f HackerNewsUutiset/pom.xml

after_success:
    - mvn clean cobertura:cobertura coveralls:report
